using pegleg.cs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace pegleg.cs.Unicode {
	public static partial class UnicodeCategories {
		

		// These methods are used to keep the file size of the autogenerated code point data from
		// getting completely out of hand.
		private static UnicodeCodePoint C(char first) { return new UnicodeCodePoint(first); }
		private static UnicodeCodePoint C(char first, char second) { return new UnicodeCodePoint(first, second); }

		public static IEnumerable<UnicodeCodePoint> All {
			get {
				return 
					UCc
					.Concat(UCf)
					.Concat(UCo)
					.Concat(UCs)
					.Concat(ULl)
					.Concat(ULm)
					.Concat(ULo)
					.Concat(ULt)
					.Concat(ULu)
					.Concat(UMc)
					.Concat(UMe)
					.Concat(UMn)
					.Concat(UNd)
					.Concat(UNl)
					.Concat(UNo)
					.Concat(UPc)
					.Concat(UPd)
					.Concat(UPe)
					.Concat(UPf)
					.Concat(UPi)
					.Concat(UPo)
					.Concat(UPs)
					.Concat(USc)
					.Concat(USk)
					.Concat(USm)
					.Concat(USo)
					.Concat(UZl)
					.Concat(UZp)
					.Concat(UZs);
			}
		}

		/// <summary>Other, Control</summary>
		public static IEnumerable<UnicodeCodePoint> Cc { get { return UCc; } }
		/// <summary>Other, Format</summary>
		public static IEnumerable<UnicodeCodePoint> Cf { get { return UCf; } }
		/// <summary>Other, Private Use</summary>
		public static IEnumerable<UnicodeCodePoint> Co { get { return UCo; } }
		/// <summary>Other, Surrogate</summary>
		public static IEnumerable<UnicodeCodePoint> Cs { get { return UCs; } }
		/// <summary>Letter, Lowercase</summary>
		public static IEnumerable<UnicodeCodePoint> Ll { get { return ULl; } }
		/// <summary>Letter, Modifier</summary>
		public static IEnumerable<UnicodeCodePoint> Lm { get { return ULm; } }
		/// <summary>Letter, Other</summary>
		public static IEnumerable<UnicodeCodePoint> Lo { get { return ULo; } }
		/// <summary>Letter, Titlecase</summary>
		public static IEnumerable<UnicodeCodePoint> Lt { get { return ULt; } }
		/// <summary>Letter, Uppercase</summary>
		public static IEnumerable<UnicodeCodePoint> Lu { get { return ULu; } }
		/// <summary>Mark, Spacing Combining</summary>
		public static IEnumerable<UnicodeCodePoint> Mc { get { return UMc; } }
		/// <summary>Mark, Enclosing</summary>
		public static IEnumerable<UnicodeCodePoint> Me { get { return UMe; } }
		/// <summary>Mark, Nonspacing</summary>
		public static IEnumerable<UnicodeCodePoint> Mn { get { return UMn; } }
		/// <summary>Number, Decimal Digit</summary>
		public static IEnumerable<UnicodeCodePoint> Nd { get { return UNd; } }
		/// <summary>Number, Letter</summary>
		public static IEnumerable<UnicodeCodePoint> Nl { get { return UNl; } }
		/// <summary>Number, Other</summary>
		public static IEnumerable<UnicodeCodePoint> No { get { return UNo; } }
		/// <summary>Punctuation, Connector</summary>
		public static IEnumerable<UnicodeCodePoint> Pc { get { return UPc; } }
		/// <summary>Punctuation, Dash</summary>
		public static IEnumerable<UnicodeCodePoint> Pd { get { return UPd; } }
		/// <summary>Punctuation, Close</summary>
		public static IEnumerable<UnicodeCodePoint> Pe { get { return UPe; } }
		/// <summary>Punctuation, Final quote</summary>
		public static IEnumerable<UnicodeCodePoint> Pf { get { return UPf; } }
		/// <summary>Punctuation, Initial quote</summary>
		public static IEnumerable<UnicodeCodePoint> Pi { get { return UPi; } }
		/// <summary>Punctuation, Other</summary>
		public static IEnumerable<UnicodeCodePoint> Po { get { return UPo; } }
		/// <summary>Punctuation, Open</summary>
		public static IEnumerable<UnicodeCodePoint> Ps { get { return UPs; } }
		/// <summary>Symbol, Currency</summary>
		public static IEnumerable<UnicodeCodePoint> Sc { get { return USc; } }
		/// <summary>Symbol, Modifier</summary>
		public static IEnumerable<UnicodeCodePoint> Sk { get { return USk; } }
		/// <summary>Symbol, Math</summary>
		public static IEnumerable<UnicodeCodePoint> Sm { get { return USm; } }
		/// <summary>Symbol, Other</summary>
		public static IEnumerable<UnicodeCodePoint> So { get { return USo; } }
		/// <summary>Separator, Line</summary>
		public static IEnumerable<UnicodeCodePoint> Zl { get { return UZl; } }
		/// <summary>Separator, Paragraph</summary>
		public static IEnumerable<UnicodeCodePoint> Zp { get { return UZp; } }
		/// <summary>Separator, Space</summary>
		public static IEnumerable<UnicodeCodePoint> Zs { get { return UZs; } }
	}
}
